artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: frabbisw/facial-age
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_preparation:
  root_dir: artifacts/data_preparation
  data_path: artifacts/data_ingestion/face_age
  dataset_name: facial_age_prepared_dataset

model_trainer:
  root_dir: artifacts/model_trainer
  trained_model_path: artifacts/model_trainer/facial_age_detector_model
  # Using EfficientFormer-L1, a much lighter model than ViT
  model_name: "snap-research/efficientformer-l1"